// Afrika Bambaataa, 127 BPM (Needs handclaps/maracas)
export const planet_rock = [
  // Instrument 1 (kick)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 2 (snare)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 3 (cowbell)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
  ],
  // Instrument 4 (open hihat)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 5 (closed hihat)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
  ],
];

// New Order 119 BPM (needs handsclaps, midtom/midconga)
export const confusion = [
  // Instrument 1 (kick)
  [
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 2 (snare)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],

  // Instrument 3 (cowbell)
  [
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
  ],
  // Instrument 4  (open hihat)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 5 (closed hihat)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
  ],
];

// Kraftwerk 98BPM
export const trans_europe_express = [
  // Instrument 1 (kick)
  [
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 2 (snare)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 3 (cowbell)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 4 (open hihat)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 5 (closed hihat)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
  ],
];

// Jam On It 116BPM (needs rimshot claves, handclaps/maracas)
export const jam_on_it = [
  // Instrument 1 (kick)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 2 (snare)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 3 (cowbell)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 4 (open hihat)
  [
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
  ],
  // Instrument 5 (closed hihat)
  [
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
    { checked: true, active: false },
  ],
];

// 126 BPM
export const disco = [
  // Instrument 1 (kick)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 2 (snare)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],

  // Instrument 3 (cowbell)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 4 (open hihat)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
  ],
  // Instrument 5 (closed hihat)
  [
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: true, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
];

export const blank = [
  // Instrument 1 (kick)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 2 (snare)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 3 (cowbell)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 4 (open hihat)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
  // Instrument 5 (closed hihat)
  [
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
    { checked: false, active: false },
  ],
];
